### PR TITLE
Update to tokio 1.1 and mio 0.7

### PR DESCRIPTION
**Pull request by marcelbuesing**
```
cargo run --example print_frames
```
seems to indicate that only one frame is received, so there is still something not working

### CODE REVIEW

**Comment by marcelbuesing** [comment]
Ok found the issue it seems to work now. It'd be great if someone could verify this and do a short review.

**Comment by oefd** [comment]
No trouble with the print_frames example, tests passing, good stuff. ✓

**Review by oefd — APPROVED** [review]
Looks good to me; also nice to see some improvements from mio/tokio that have come around since I was last brushing up against them a lot.

**Comment by marcelbuesing** [comment]
Ok I think I will merge this. I am not entirely sure about the `clear_ready` in the `Sink` implementation after reading the [docs](https://docs.rs/tokio/1.1.0/tokio/io/unix/struct.AsyncFdReadyGuard.html#method.clear_ready).

**Pull request merged**
